<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC-20180918EPWD" name="testng.shij" tests="1" failures="0" timestamp="28 Dec 2018 00:55:53 GMT" time="4.020" errors="1">
  <testcase name="newtest" time="4.020" classname="testng.shij">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.newtest() didn&#039;t finish within the time-out 4000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.newtest() didn't finish within the time-out 4000
	at java.lang.Thread.currentThread(Native Method)
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:150)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1004)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- newtest -->
</testsuite> <!-- testng.shij -->
